# cluster-cancel: "scancel"
# restart-times: "0"
# jobscript: "slurm-jobscript.sh"
# cluster: "slurm-submit.py"
# cluster-status: "slurm-status.py"
# max-jobs-per-second: "10"
# max-status-checks-per-second: "10"
# local-cores: 1
# latency-wait: "60"
# use-conda: "True"
# use-singularity: "False"
# jobs: 500
# printshellcmds: "True"

# config.yaml (in your slurm profile)
executor: slurm
jobs: 500
latency-wait: 60
use-conda: true
printshellcmds: true

default-resources:
  - runtime=60
  - mem_mb=4000

restart-times: 0

